<#import "/spring.ftl" as spring />
<#import "/macros/layout.ftl" as lo />
<#import "/macros/box.ftl" as bx />
<#import "/macros/head.ftl" as hd />
<#import "/macros/swf.ftl" as fl />
<#import "/macros/cancelForm.ftl" as cf />
<@spring.bind "identityForm.credential.*" /> 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<@hd.head "Personal Data">
	  <link href="style-blue.css" rel="stylesheet" />
</@hd.head>
<body>
<div style="height: 120px;"></div>

<div id="layout">

	<div id="header">
	<p>Your identity
	<#if identityForm.credential.identity.principal!=""> 
	is <b>${identityForm.credential.identity.principal}</b></p>
	<#else>
	will be generated by the system.
	</#if>
	</div>

	<div id="sidebar">
	
		<h2>Personal Data</h2>
	
		<p>Please, add your personal data.</p>

		<#assign page=1/>
		<@cf.cancelForm "admin.htm"/>

	</div>
	
	<div id="main">
	
		<div id="navigator" style="position: relative; float: right;">
			<h3>Summary</h3>
			<#include "summary.ftl"/>
		</div>
		
		<form action="admin.htm" method="POST">
		<@bx.table "${identityForm.credential.identity.principal}">
	
		<@bx.group>
			<@bx.row>Optional alias:</@bx.row>
			<@bx.row>
			<@spring.formInput "identityForm.credential.identity.optionalAlias", 'size="32"'/>
			</@bx.row>
		</@bx.group>

		<@bx.group >
			<@bx.row>First name:</@bx.row>
			<@bx.row>
			<@spring.formInput "identityForm.credential.identity.personalData.firstName", 'size="32"' />
			</@bx.row>
		</@bx.group>

		<@bx.group >
			<@bx.row>Last name:</@bx.row>
			<@bx.row>
			<@spring.formInput "identityForm.credential.identity.personalData.lastName", 'size="32"' />
			</@bx.row>
		</@bx.group>
		
		<#include "/core/options/gender.ftl"/>
		
		<@bx.group >
			<@bx.row>Gender:</@bx.row>
			<@bx.row>
			<@spring.formSingleSelect "identityForm.credential.identity.personalData.gender", gender />
			</@bx.row>
		</@bx.group>
		
		<#include "/core/options/appellation.ftl"/>
		
		<@bx.group >
			<@bx.row>Appellation:</@bx.row>
			<@bx.row>
			<@spring.formSingleSelect "identityForm.credential.identity.personalData.appellation", appellation />
			</@bx.row>
		</@bx.group>
		
		
		<tr>
		<@fl.submit "previous"/>
		<@fl.submit "next"/>
		</tr>

		<@fl.flowKey/>
		
		</@bx.table>
		</form>
				
	</div>

</div>
</body>
</html>
